export const site = {
  name: "Boxe Thaï",
  domain: "boxe-thai.com",
  url: "https://boxe-thai.com",
  locale: "fr_FR",
  language: "fr-FR",
  tagline: "Le guide de la boxe thaï et du Muay Thaï",
  description:
    "Site de référence sur la boxe thaï et le Muay Thaï : techniques, entraînement, débutant, histoire et cours à Toulouse.",
  email: "boxingcenter31@gmail.com",
  phoneDisplay: "05 62 24 46 82",
  phoneHref: "+33562244682",
  boxingCenterUrl: "https://boxingcenter.fr/",
  boxingCenterThaiUrl:
    "https://boxingcenter.fr/boxe-thai-muay-thai-et-kick-boxing-toulouse/",
  openingHours: "Mo-Sa 10:00-21:30",
  openingHoursLabel: "Lundi au samedi · 10h00 – 21h30",
} as const;

export const boxingCenter = {
  name: "Boxing Center",
  founded: 2016,
  affiliation: "FFKMDA",
  hours: "Lundi au samedi, 10h00 – 21h30",
  phone: site.phoneDisplay,
  email: site.email,
  url: site.boxingCenterUrl,
  thaiUrl: site.boxingCenterThaiUrl,
  salles: [
    {
      slug: "saint-cyprien",
      name: "Toulouse Saint-Cyprien",
      focus: "Boxe thaï / K1 en centre-ville",
      address: "11 rue Sainte-Lucie",
      postalCode: "31300",
      city: "Toulouse",
      note: "Salle de centre-ville, ouverte le 10 janvier 2022. Créneaux labellisés Boxe Thaï / K1.",
      image: "/images/salles/saint-cyprien-hero.webp",
      mapQuery: "11+rue+Sainte+Lucie+31300+Toulouse",
    },
    {
      slug: "etats-unis",
      name: "Toulouse États-Unis",
      focus: "Plus grand espace combat, boxe pieds-poings",
      address: "388 avenue des États-Unis",
      postalCode: "31200",
      city: "Toulouse",
      note: "Grande salle dédiée aux sports de combat, avec espaces boxe, striking et préparation physique.",
      image: "/images/salles/etats-unis-hero.webp",
      mapQuery: "388+Avenue+des+Etats-Unis+31200+Toulouse",
    },
    {
      slug: "minimes",
      name: "Toulouse Minimes",
      focus: "Barrière de Paris — Minimes",
      address: "12 rue de Fenouillet",
      postalCode: "31200",
      city: "Toulouse",
      note: "Salle Boxing Center située Barrière de Paris / Minimes.",
      image: "/images/salles/etats-unis-espace.webp",
      mapQuery: "12+rue+de+Fenouillet+31200+Toulouse",
    },
    {
      slug: "ramonville",
      name: "Ramonville-Saint-Agne",
      focus: "Boxe et boxe éducative",
      address: "33 rue des Ormes",
      postalCode: "31520",
      city: "Ramonville-Saint-Agne",
      note: "Club Boxing Center à Ramonville-Saint-Agne.",
      image: "/images/salles/saint-cyprien-espace.webp",
      mapQuery: "33+rue+des+Ormes+31520+Ramonville-Saint-Agne",
    },
    {
      slug: "portet",
      name: "Portet-sur-Garonne",
      focus: "Boxe et préparation physique",
      address: "61 route d’Espagne",
      postalCode: "31120",
      city: "Portet-sur-Garonne",
      note: "Salle Boxing Center à Portet-sur-Garonne.",
      image: "/images/salles/etats-unis-gants.webp",
      mapQuery: "61+route+d+Espagne+31120+Portet-sur-Garonne",
    },
  ],
  coachesThai: [
    {
      name: "Jérôme",
      role: "Boxe thaï et MMA",
      bio: "Spécialiste de la boxe thaï et du MMA, il a combattu professionnellement au Canada et en Thaïlande. Il enseigne au Boxing Center à Toulouse.",
      image: "/images/coaches/coach-jerome.webp",
    },
    {
      name: "Renaud",
      role: "Boxe pieds-poings · Kick-boxing",
      bio: "Plusieurs fois champion de France en full-contact et kick-boxing. Coach référent en boxe pieds-poings à Toulouse États-Unis.",
      image: "/images/coaches/coach-renaud.webp",
    },
    {
      name: "Sonia",
      role: "Boxe thaï · Boxing Lady",
      bio: "Enseigne la boxe thaï, le Boxing Lady et le Boxing Camp, notamment à la salle des Minimes.",
      image: "/images/entrainement/boxe-thai-2.webp",
    },
  ],
  saintCyprienSchedule: [
    { day: "Mardi", slots: ["12h40 – 13h20", "20h00 – 21h15"] },
    { day: "Jeudi", slots: ["12h40 – 13h20", "20h00 – 21h15"] },
    { day: "Vendredi", slots: ["19h00 – 20h00"] },
    { day: "Samedi", slots: ["18h20 – 20h00"] },
  ],
} as const;

export const nav = {
  primary: [
    { href: "/boxe-thai/", label: "La discipline" },
    { href: "/techniques-boxe-thai/", label: "Techniques" },
    { href: "/boxe-thai-debutant/", label: "Débutant" },
    { href: "/boxe-thai-toulouse/", label: "Toulouse" },
    { href: "/galerie/", label: "Galerie" },
    { href: "/blog/", label: "Blog" },
    { href: "/faq/", label: "FAQ" },
  ],
  discipline: [
    { href: "/boxe-thai/", label: "Qu’est-ce que la boxe thaï ?" },
    { href: "/muay-thai/", label: "Muay Thaï" },
    { href: "/histoire-boxe-thai/", label: "Histoire" },
    { href: "/techniques-boxe-thai/", label: "Techniques" },
  ],
  pratiquer: [
    { href: "/boxe-thai-debutant/", label: "Débuter" },
    { href: "/entrainement-boxe-thai/", label: "Entraînement" },
    { href: "/equipement-boxe-thai/", label: "Équipement" },
    { href: "/boxe-thai-femme/", label: "Boxe thaï femme" },
  ],
  toulouse: [
    { href: "/boxe-thai-toulouse/", label: "Boxe thaï à Toulouse" },
    { href: "/club-boxe-thai-toulouse/", label: "Club" },
    { href: "/cours-boxe-thai-toulouse/", label: "Cours" },
  ],
  footer: [
    { href: "/boxe-thai/", label: "Boxe thaï" },
    { href: "/muay-thai/", label: "Muay Thaï" },
    { href: "/histoire-boxe-thai/", label: "Histoire" },
    { href: "/techniques-boxe-thai/", label: "Techniques" },
    { href: "/entrainement-boxe-thai/", label: "Entraînement" },
    { href: "/boxe-thai-debutant/", label: "Débutant" },
    { href: "/equipement-boxe-thai/", label: "Équipement" },
    { href: "/boxe-thai-femme/", label: "Femme" },
    { href: "/boxe-thai-toulouse/", label: "Toulouse" },
    { href: "/club-boxe-thai-toulouse/", label: "Club Toulouse" },
    { href: "/cours-boxe-thai-toulouse/", label: "Cours Toulouse" },
    { href: "/galerie/", label: "Galerie" },
    { href: "/blog/", label: "Blog" },
    { href: "/faq/", label: "FAQ" },
  ],
} as const;

export type Crumb = { href?: string; label: string };
